// frontend/src/components/native/SortableTh.vue
<template>
  <button
    type="button"
    class="kn-sort-th"
    :class="{ 'is-numeric': numeric, 'is-active': active }"
    :aria-sort="active ? (desc ? 'descending' : 'ascending') : 'none'"
    @click="$emit('sort')"
  >
    <span class="kn-sort-label">{{ label }}</span>
    <span class="kn-sort-carets" aria-hidden="true">
      <svg viewBox="0 0 16 16" width="11" height="11" class="kn-sort-caret">
        <path
          class="kn-caret-up"
          :class="{ 'is-on': active && !desc }"
          d="M8 3.5 12 8H4z"
          fill="currentColor"
        />
        <path
          class="kn-caret-down"
          :class="{ 'is-on': active && desc }"
          d="M8 12.5 4 8h8z"
          fill="currentColor"
        />
      </svg>
    </span>
  </button>
</template>

<script setup>
defineProps({
  field: { type: String, required: true },
  label: { type: String, required: true },
  active: { type: Boolean, default: false },
  desc: { type: Boolean, default: false },
  numeric: { type: Boolean, default: false },
})

defineEmits(['sort'])
</script>

<style scoped>
.kn-sort-th {
  display: inline-flex;
  align-items: center;
  gap: 0.25rem;
  width: 100%;
  padding: 0;
  margin: 0;
  border: 0;
  background: none;
  font: inherit;
  font-weight: 600;
  color: var(--native-muted);
  white-space: nowrap;
  cursor: pointer;
  user-select: none;
  transition: color 0.15s;
}
.kn-sort-th:hover {
  color: var(--native-foreground);
}
.kn-sort-th.is-active {
  color: var(--native-primary);
}
.kn-sort-th.is-numeric {
  justify-content: flex-end;
}
.kn-sort-label {
  overflow: hidden;
  text-overflow: ellipsis;
}
.kn-sort-carets {
  display: inline-flex;
  flex-shrink: 0;
  line-height: 0;
}
.kn-sort-caret {
  display: block;
}
.kn-caret-up,
.kn-caret-down {
  opacity: 0.28;
  transition: opacity 0.15s;
}
.kn-caret-up.is-on,
.kn-caret-down.is-on {
  opacity: 1;
  color: var(--native-primary);
}
</style>

// frontend-react/src/components/ui/SortableTh.tsx
// 三态升降表头按钮（移植自 Vue components/native/SortableTh.vue，玻璃风格）。
// 父组件负责 none→asc→desc→none 的三态循环（onSort）；本组件只负责渲染 + aria-sort。
// 见 research/pr2-need-pages.md §4。

interface SortableThProps {
  field: string
  label: string
  active?: boolean
  desc?: boolean
  /** 数字列右对齐 */
  numeric?: boolean
  onSort: (field: string) => void
}

export function SortableTh({ field, label, active = false, desc = false, numeric = false, onSort }: SortableThProps) {
  const ariaSort = active ? (desc ? 'descending' : 'ascending') : 'none'
  const upOn = active && !desc
  const downOn = active && desc

  return (
    <button
      type="button"
      onClick={() => onSort(field)}
      aria-sort={ariaSort}
      className={`inline-flex items-center gap-1 cursor-pointer bg-transparent border-none p-0 font-semibold transition-colors focus:outline-none focus-visible:ring-2 focus-visible:ring-apple-blue rounded ${
        numeric ? 'flex-row-reverse' : ''
      } ${active ? 'text-apple-blue' : 'text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-200'}`}
    >
      <span>{label}</span>
      <span className="inline-flex flex-col leading-none" aria-hidden="true">
        <svg className={`w-2.5 h-2.5 -mb-0.5 ${upOn ? 'text-apple-blue' : 'text-gray-300 dark:text-gray-600'}`} viewBox="0 0 12 12" fill="currentColor">
          <path d="M6 2.5L9.5 7.5h-7z" />
        </svg>
        <svg className={`w-2.5 h-2.5 ${downOn ? 'text-apple-blue' : 'text-gray-300 dark:text-gray-600'}`} viewBox="0 0 12 12" fill="currentColor">
          <path d="M6 9.5L2.5 4.5h7z" />
        </svg>
      </span>
    </button>
  )
}
